### ISSUE TITLE
GitHub Actionsのデプロイ時に環境変数を設定

### ISSUE THREAD

**Issue by sugasaki** [sugasaki/gpx-route-creator#16]
## 概要
GitHub Actionsのデプロイワークフローで、MapTiler APIキーを環境変数として設定する必要があります。
現在、地図スタイル切り替え機能でMapTilerのスタイルを使用する際にAPIキーが必要ですが、デプロイ時に環境変数が設定されていません。

## 現状
- `.github/workflows/deploy.yml`にビルドとデプロイの設定が存在
- ビルドステップで`NODE_ENV=production`のみが設定されている
- `VITE_MAPTILER_KEY`環境変数が設定されていない

### 1. GitHub Secretsの設定（手動作業）
リポジトリの Settings > Secrets and variables > Actions で以下を設定：
- Secret名: `VITE_MAPTILER_KEY`
- 値: MapTilerのAPIキー

### 2. deploy.ymlの更新
```yaml
- name: Build
  run: pnpm build
  env:
    NODE_ENV: production
    VITE_MAPTILER_KEY: ${{ secrets.VITE_MAPTILER_KEY }}
```

## 実装詳細
現在のdeploy.yml（39-42行目）:
```yaml
- name: Build
  run: pnpm build
  env:
    NODE_ENV: production
```

これを以下のように更新：
```yaml
- name: Build
  run: pnpm build
  env:
    NODE_ENV: production
    VITE_MAPTILER_KEY: ${{ secrets.VITE_MAPTILER_KEY }}
```

## セキュリティ考慮事項
- APIキーはGitHub Secretsに保存し、ログに出力されないよう保護
- Viteの環境変数は`VITE_`プレフィックスが必要（クライアントサイドで使用するため）
- ビルド時にのみ必要で、実行時には不要

## 関連
- #14 地図スタイルを切り替える機能の追加

## 優先度
高（地図スタイル切り替え機能の動作に必要）
